import { INoticia } from "../../../interfaces/inoticia.interface";

export const noticiasNoPublicadas: INoticia[] = [
    {
        id: 26,
        titular: "Exploración de nuevos exoplanetas habitables",
        imagen: "https://example.com/images/exoplanetas.jpg",
        texto: "Astrónomos han descubierto varios exoplanetas que podrían tener condiciones similares a las de la Tierra.",
        secciones: "destacado",
        fecha_publicacion: "2024-11-20",
        redactor_id: "R026",
        editor_id: "E026",
        categoria_id: "C026",
        estado: "No Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-15"),
        slug: "exploracion-exoplanetas-habitables"
    },
    {
        id: 27,
        titular: "Revolución en los sistemas de reciclaje urbano",
        imagen: "https://example.com/images/reciclaje.jpg",
        texto: "Un nuevo sistema automatizado promete aumentar la eficiencia del reciclaje en grandes ciudades.",
        secciones: "general",
        fecha_publicacion: "2024-11-22",
        redactor_id: "R027",
        editor_id: "E027",
        categoria_id: "C027",
        estado: "No Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-14"),
        slug: "revolucion-reciclaje-urbano"
    },
    {
        id: 28,
        titular: "El impacto del turismo espacial en el medio ambiente",
        imagen: "https://example.com/images/turismo-espacial.jpg",
        texto: "Expertos están analizando las consecuencias del turismo espacial en la atmósfera terrestre.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-25",
        redactor_id: "R028",
        editor_id: "E028",
        categoria_id: "C028",
        estado: "No Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-16"),
        slug: "impacto-turismo-espacial"
    },
    {
        id: 29,
        titular: "Innovaciones en vehículos eléctricos para 2025",
        imagen: "https://example.com/images/vehiculos-electricos.jpg",
        texto: "Los fabricantes han anunciado una nueva generación de vehículos eléctricos con mayor autonomía.",
        secciones: "general",
        fecha_publicacion: "2024-11-18",
        redactor_id: "R029",
        editor_id: "E029",
        categoria_id: "C029",
        estado: "No Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-15"),
        slug: "innovaciones-vehiculos-electricos"
    },
    {
        id: 30,
        titular: "Avances en biotecnología para combatir enfermedades raras",
        imagen: "https://example.com/images/biotecnologia.jpg",
        texto: "Científicos están desarrollando tratamientos innovadores para enfermedades que afectan a pocas personas.",
        secciones: "destacado",
        fecha_publicacion: "2024-11-19",
        redactor_id: "R030",
        editor_id: "E030",
        categoria_id: "C030",
        estado: "No Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-12"),
        slug: "avances-biotecnologia-enfermedades-raras"
    },
    {
        id: 31,
        titular: "Reformas en el sistema educativo europeo",
        imagen: "https://example.com/images/educacion-europa.jpg",
        texto: "La Unión Europea planea implementar reformas para modernizar la educación en los próximos años.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-21",
        redactor_id: "R031",
        editor_id: "E031",
        categoria_id: "C031",
        estado: "No Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-13"),
        slug: "reformas-sistema-educativo-europeo"
    },
    {
        id: 32,
        titular: "El futuro de los combustibles sintéticos",
        imagen: "https://example.com/images/combustibles-sinteticos.jpg",
        texto: "La industria energética explora combustibles sintéticos como una alternativa sostenible.",
        secciones: "general",
        fecha_publicacion: "2024-11-24",
        redactor_id: "R032",
        editor_id: "E032",
        categoria_id: "C032",
        estado: "No Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-14"),
        slug: "futuro-combustibles-sinteticos"
    },
    {
        id: 33,
        titular: "La influencia de los videojuegos en la creatividad infantil",
        imagen: "https://example.com/images/videojuegos-creatividad.jpg",
        texto: "Un nuevo estudio revela cómo los videojuegos pueden potenciar el pensamiento creativo en niños.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-26",
        redactor_id: "R033",
        editor_id: "E033",
        categoria_id: "C033",
        estado: "No Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-16"),
        slug: "videojuegos-creatividad-infantil"
    },
    {
        id: 34,
        titular: "Nuevas estrategias para combatir la contaminación plástica",
        imagen: "https://example.com/images/contaminacion-plastica.jpg",
        texto: "Organizaciones ambientales están implementando soluciones innovadoras para reducir el plástico en los océanos.",
        secciones: "destacado",
        fecha_publicacion: "2024-11-23",
        redactor_id: "R034",
        editor_id: "E034",
        categoria_id: "C034",
        estado: "No Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-15"),
        slug: "estrategias-combatir-contaminacion-plastica"
    },
    {
        id: 35,
        titular: "El auge de la robótica en la agricultura",
        imagen: "https://example.com/images/robotica-agricultura.jpg",
        texto: "La automatización está transformando la manera en que se cultivan y cosechan los alimentos.",
        secciones: "general",
        fecha_publicacion: "2024-11-27",
        redactor_id: "R035",
        editor_id: "E035",
        categoria_id: "C035",
        estado: "No Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-16"),
        slug: "auge-robotica-agricultura"
    }
];
