import { INoticia } from "../../interfaces/inoticia.interface";

export const NOTICIAS: INoticia[] = [
    {
        id: 11,
        titular: "La inteligencia artificial llega al cine",
        imagen: "https://example.com/images/ia-cine.jpg",
        texto: "La inteligencia artificial está siendo utilizada para crear guiones y efectos especiales en la industria cinematográfica.",
        secciones: "general",
        fecha_publicacion: "2024-11-10",
        redactor_id: "R011",
        editor_id: "E011",
        categoria_id: "C011",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-05"),
        slug: "ia-llega-al-cine"
    },
    {
        id: 12,
        titular: "Reducción de emisiones en la industria automotriz",
        imagen: "https://example.com/images/automotriz.jpg",
        texto: "Los fabricantes de autos están implementando nuevas tecnologías para reducir la huella de carbono de sus vehículos.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-13",
        redactor_id: "R012",
        editor_id: "E012",
        categoria_id: "C012",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-11"),
        slug: "reduccion-emisiones-industria-automotriz"
    },
    {
        id: 13,
        titular: "Cambio de paradigma en el transporte público",
        imagen: "https://example.com/images/transporte-publico.jpg",
        texto: "Ciudades alrededor del mundo están implementando nuevos modelos de transporte más ecológicos y accesibles.",
        secciones: "general",
        fecha_publicacion: "2024-11-09",
        redactor_id: "R013",
        editor_id: "E013",
        categoria_id: "C013",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-07"),
        slug: "cambio-paradigma-transporte-publico"
    },
    {
        id: 14,
        titular: "La agricultura vertical toma fuerza en ciudades",
        imagen: "https://example.com/images/agricultura-vertical.jpg",
        texto: "Empresas están creando granjas en rascacielos para producir alimentos frescos en el corazón de las ciudades.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-06",
        redactor_id: "R014",
        editor_id: "E014",
        categoria_id: "C014",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-03"),
        slug: "agricultura-vertical-ciudades"
    },
    {
        id: 15,
        titular: "La neurociencia avanza en el estudio del cerebro",
        imagen: "https://www.lavozdegalicia.es/default/2020/08/11/00121597156982248194621/Foto/EG12P48F2_164153.jpg",
        texto: "Investigadores han logrado mapear por primera vez la actividad cerebral de forma más precisa.",
        secciones: "destacado",
        fecha_publicacion: "2024-11-12",
        redactor_id: "R015",
        editor_id: "E015",
        categoria_id: "C015",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-10"),
        slug: "neurociencia-estudio-cerebro"
    },
    {
        id: 16,
        titular: "Las criptomonedas en 2024: lo que se viene",
        imagen: "https://example.com/images/criptomonedas.jpg",
        texto: "Las criptomonedas continúan ganando terreno en los mercados financieros y en el comercio global.",
        secciones: "general",
        fecha_publicacion: "2024-11-11",
        redactor_id: "R016",
        editor_id: "E016",
        categoria_id: "C016",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-08"),
        slug: "criptomonedas-en-2024"
    },
    {
        id: 17,
        titular: "Nuevas leyes para proteger la privacidad digital",
        imagen: "https://example.com/images/privacidad-digital.jpg",
        texto: "Diversos países están aprobando leyes más estrictas para proteger la privacidad en línea de los usuarios.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-04",
        redactor_id: "R017",
        editor_id: "E017",
        categoria_id: "C017",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-02"),
        slug: "nuevas-leyes-privacidad-digital"
    },
    {
        id: 18,
        titular: "El impacto de la pandemia en la salud mental",
        imagen: "https://example.com/images/salud-mental.jpg",
        texto: "Especialistas alertan sobre el aumento de trastornos mentales derivados de la pandemia de COVID-19.",
        secciones: "general",
        fecha_publicacion: "2024-11-10",
        redactor_id: "R018",
        editor_id: "E018",
        categoria_id: "C018",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-06"),
        slug: "impacto-pandemia-salud-mental"
    },
    {
        id: 19,
        titular: "La energía solar alcanza nuevos niveles de eficiencia",
        imagen: "https://i.ytimg.com/vi/WGTiTY9cVOU/maxresdefault.jpg",
        texto: "Los avances tecnológicos permiten ahora generar más energía solar con menos recursos.",
        secciones: "destacado",
        fecha_publicacion: "2024-11-14",
        redactor_id: "R019",
        editor_id: "E019",
        categoria_id: "C019",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-13"),
        slug: "energia-solar-nuevos-avances"
    },
    {
        id: 20,
        titular: "Revolución en el mercado de los videojuegos",
        imagen: "https://example.com/images/videojuegos.jpg",
        texto: "Los videojuegos han evolucionado hacia experiencias inmersivas con el uso de realidad virtual.",
        secciones: "general",
        fecha_publicacion: "2024-11-12",
        redactor_id: "R020",
        editor_id: "E020",
        categoria_id: "C020",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-09"),
        slug: "revolucion-videojuegos-realidad-virtual"
    },
    {
        id: 21,
        titular: "La influencia de las redes sociales en la política moderna",
        imagen: "https://example.com/images/redes-sociales.jpg",
        texto: "Las redes sociales están transformando la manera en que los políticos interactúan con el electorado.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-05",
        redactor_id: "R021",
        editor_id: "E021",
        categoria_id: "C021",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-03"),
        slug: "redes-sociales-politica-moderna"
    },
    {
        id: 22,
        titular: "El futuro del trabajo post-pandemia",
        imagen: "https://example.com/images/futuro-trabajo.jpg",
        texto: "El teletrabajo y las herramientas digitales están redefiniendo la dinámica laboral a nivel global.",
        secciones: "general",
        fecha_publicacion: "2024-11-13",
        redactor_id: "R022",
        editor_id: "E022",
        categoria_id: "C022",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-11"),
        slug: "futuro-del-trabajo-post-pandemia"
    },
    {
        id: 23,
        titular: "Cómo las empresas están adoptando la sostenibilidad",
        imagen: "https://example.com/images/sostenibilidad.jpg",
        texto: "Cada vez más compañías están integrando prácticas ecológicas en sus modelos de negocio.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-09",
        redactor_id: "R023",
        editor_id: "E023",
        categoria_id: "C023",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-07"),
        slug: "empresas-adoptan-sostenibilidad"
    },
    {
        id: 24,
        titular: "Los efectos del cambio climático en los océanos",
        imagen: "https://s2.ppllstatics.com/elcorreo/www/multimedia/201811/30/media/cangreburguer-Bob-Esponja.jpg",
        texto: "El aumento de la temperatura global está afectando la vida marina y los ecosistemas oceánicos.",
        secciones: "destacado",
        fecha_publicacion: "2024-11-14",
        redactor_id: "R024",
        editor_id: "E024",
        categoria_id: "C024",
        estado: "Publicado",
        importancia: "Alta",
        cambios: new Date("2024-11-12"),
        slug: "efectos-cambio-climatico-oceanos"
    },
    {
        id: 25,
        titular: "La evolución de la inteligencia artificial en la educación",
        imagen: "https://example.com/images/ia-educacion.jpg",
        texto: "Las aplicaciones de la inteligencia artificial están revolucionando la enseñanza y el aprendizaje.",
        secciones: "secundario",
        fecha_publicacion: "2024-11-07",
        redactor_id: "R025",
        editor_id: "E025",
        categoria_id: "C025",
        estado: "Publicado",
        importancia: "Media",
        cambios: new Date("2024-11-06"),
        slug: "evolucion-ia-educacion"
    }
];
